# Generated by Django 3.1.3 on 2020-11-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.component')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.pack')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='components',
            field=models.ManyToManyField(through='packs.PackComponent', to='packs.Component'),
        ),
        migrations.AddField(
            model_name='component',
            name='packs',
            field=models.ManyToManyField(through='packs.PackComponent', to='packs.Pack'),
        ),
    ]
