# Generated by Django 3.1.3 on 2020-11-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='name',
            new_name='component_name',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='name',
            new_name='pack_name',
        ),
    ]
